# -*- coding: utf-8 -*-
"""Day 3 Extension

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UlA-iXllLJukA_JEY0JLX4oAlRfFg-bS

**LOADING THE DATA**
"""

import pandas as pd
from google.colab import files
uploaded = files.upload()

"""**READING THE DATA INTO A DATAFRAME**"""

df = pd.read_csv('student_python_task.csv')
df.head()
#This is used to show a sample of the data to see if the import has worked correctly
#without showing the file as a whole to save time and cpu

#(df[df['mark']>70][['name', 'mark']])
#This shows all the names of students with marks above 70
#The problem this is solving maybe to show all the students
#who have passed an exam

"""**INSPECTING THE DATA**"""

df.info()
#This shows the column names, data types and the number of data points in each column
#It is an important sanity check to inspect the data and make sure it is how you expect

"""**SHOWING STUDENTS WITH A MARK HIGHER THAN 70**"""

(df[df['mark']>70][['name', 'mark']])
#This shows all the names of students with marks above 70
#The problem this is solving maybe to show all the students
#who have passed an exam

"""**What is the typical student mark, and what are the lowest and highest mark?**"""

# Calculate the typical (mean) student mark
typical_mark = df['mark'].mean()
print(f"Average student mark {typical_mark:.2f}")

# Calculate the lowest student mark
lowest_mark = df['mark'].min()
print(f"Lowest student mark: {lowest_mark}")

# Calculate the highest student mark
highest_mark = df['mark'].max()
print(f"Highest student mark: {highest_mark}")

#Calculate the median student mark
median_mark = df['mark'].median()
print(f"Median student mark: {median_mark}")

#The median mark is good to use when there are outliers
#as it shows the middle result regardless of the extreme
#high or low values whereas the mean is easily distorted

df['gender'].value_counts()
#This shows the dataframe is quite evenly split
#between female and male student data

df.rename(columns= {'name' : 'student'}, inplace=True)
df.rename(columns= {'mark' : 'test_score'}, inplace=True)

df.head()

df.to_csv("test_score_summary.csv", index=False)
print("DataFrame exported to 'test_score_summary.csv'")

student_test_scores_df = df[['student', 'test_score']]
student_test_scores_df.to_csv('student_test_scores.csv', index=False)
print("DataFrame with 'student' and 'test_score' exported to 'student_test_scores.csv'")
student_test_scores_df.head()